---
- name: Apply faillock config
  template:
    src: auth_faillock.conf.j2
    dest: /etc/security/faillock.conf
    mode: 0640
  become: true

- name: Apply pwquality config
  template:
    src: auth_pwquality.conf.j2
    dest: /etc/security/pwquality.conf
    mode: 0640
  become: true

- name: Enbale faillock
  command: authselect enable-feature with-faillock
  become: true
