---
- block:
    - name: Update login.defs settings
      block:
        - name: Set home mode to 0700
          lineinfile:
            path: /etc/login.defs
            regexp: ^#?HOME_MODE
            line: HOME_MODE 0700
            state: present
            backrefs: true
        - name: Improve password hashing security
          lineinfile:
            path: /etc/login.defs
            regexp: ^#?YESCRYPT_COST_FACTOR
            line: YESCRYPT_COST_FACTOR {{ HARDENING_YESCTYPT_HOST_FACTOR }}
            state: present
            backrefs: true
      become: true

    - name: Blacklist unused modules
      copy:
        src: hardening_modules_blacklist.conf
        dest: /etc/modprobe.d/blacklist.conf
        mode: 0640
      become: true

    - name: Hardening kernel settings
      copy:
        src: hardening_kernel.conf
        dest: /etc/sysctl.d/hardening.conf
        mode: 0640
      become: true

    - name: Disable core dumps
      copy:
        src: hardening_systemd_coredump.conf
        dest: /etc/systemd/coredump.conf
        mode: 0640
      become: true
