---
- name: Base hardening task
  import_tasks: hardening.yml
  when: HARDENING_CONFIG_ENABLED
  tags: hardening

- name: Config SSH
  import_tasks: ssh.yml
  when: SSH_CONFIG_ENABLED
  tags: ssh

- name: Install and config fail2ban
  import_tasks: fail2ban.yml
  when: FAIL2BAN_ENABLED
  tags: fail2ban
