---
- name: Base hardening task
  import_tasks: hardening.yml
  when: HARDENING_CONFIG_ENABLED
  tags: hardening

- name: Tasks for Debian-based systems
  import_tasks: debian.yml
  when:
    - DEBIAN_HARDENING_ENABLED
    - ansible_os_family == "Debian"
  tags: debian

- name: Tasks for RedHat-based systems
  import_tasks: redhat.yml
  when:
    - REDHAT_HARDENING_ENABLED
    - ansible_os_family == "RedHat"
  tags: redhat

- name: Config SSH
  import_tasks: ssh.yml
  when: SSH_CONFIG_ENABLED
  tags: ssh

- name: Install and config fail2ban
  import_tasks: fail2ban.yml
  when: FAIL2BAN_ENABLED
  tags: fail2ban

- name: Install and config chrony
  import_tasks: chrony.yml
  when: CHRONY_ENABLED
  tags: chrony
