---
- block:
    - name: Update login.defs settings
      block:
        - name: Set home mode to 0700
          lineinfile:
            path: /etc/login.defs
            regexp: ^#?HOME_MODE
            line: HOME_MODE 0700
            state: present
            backrefs: true
        - name: Improve password hashing security
          lineinfile:
            path: /etc/login.defs
            regexp: ^#?YESCRYPT_COST_FACTOR
            line: YESCRYPT_COST_FACTOR {{ HARDENING_MISC_YESCRYPT_HOST_FACTOR }}
            state: present
            backrefs: true
      become: true

    - name: Set permissions for {{ USERNAME }}'s home directory
      file:
        path: /home/{{ USERNAME }}
        state: directory
        mode: 0750
        owner: '{{ USERNAME }}'
        group: '{{ USERNAME }}'
      become: true

    - name: Blacklist unused modules
      template:
        src: misc_modules_blacklist.conf.j2
        dest: /etc/modprobe.d/blacklist.conf
        mode: 0640
      become: true

    - name: Hardening kernel settings
      template:
        src: misc_kernel.conf.j2
        dest: /etc/sysctl.d/hardening.conf
        mode: 0640
      become: true

    - name: Disable core dumps
      copy:
        src: misc_systemd_coredump.conf
        dest: /etc/systemd/coredump.conf
        mode: 0640
      become: true
