---
- name: DNF disable countme
  copy:
    src: redhat_dnf_disable_countme.conf
    dest: /etc/dnf/libdnf5.conf.d/dnf_disable_countme.conf
    mode: 0644
  become: true

- name: Install python3-libdnf5
  shell: rpm -q python3-libdnf5 || dnf install --setopt=install_weak_deps=False --assumeyes python3-libdnf5
  changed_when: false
  become: true

- name: Update RedHat-based system
  dnf:
    name: '*'
    state: latest
    update_cache: true
    install_weak_deps: false
  become: true

- name: Autoremove pkgs
  dnf:
    autoremove: true
  become: true
