---
- name: DNF disable countme on RedHat family system
  blockinfile:
    path: /etc/dnf/dnf.conf
    block: |
      countme=False
    marker: '# {mark} ANSIBLE HARDENING'
  become: true
  when: ansible_distribution in ["RedHat", "Alma", "AlmaLinux", "Rocky", "RockyLinux"]

- name: DNF disable countme on Fedora
  copy:
    src: redhat_dnf_disable_countme.conf
    dest: /etc/dnf/libdnf5.conf.d/dnf_disable_countme.conf
    mode: 0644
  become: true
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version | int >= 41

- name: Install python3-libdnf5
  shell: rpm -q python3-libdnf5 || dnf install -y python3-libdnf5
  changed_when: false
  become: true
  when:
    - ansible_distribution == "Fedora"
    - ansible_distribution_major_version | int >= 41

- name: Install python3-libdnf
  shell: rpm -q python3-libdnf || dnf install -y python3-libdnf
  changed_when: false
  become: true
  when: ansible_distribution in ["RedHat", "Alma", "AlmaLinux", "Rocky", "RockyLinux"]

- name: Update RedHat family system
  dnf:
    name: '*'
    state: latest
    update_cache: true
    install_weak_deps: false
  become: true

- name: Autoremove pkgs
  dnf:
    autoremove: true
  become: true
